language: node_js
node_js: node
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_success: yarn coverage
after_script: greenkeeper-lockfile-upload
branches:
  only:
    - master
    - /^greenkeeper/.*$/